### ISSUE TITLE
Mono can switch colors, even though it's not unlocked yet.

### ISSUE THREAD

**Issue by rocketbucket10** [teamspettro/monospace-game-bugs#4]
https://streamable.com/qotnq3

https://streamable.com/krrpwm

**Comment by NextinMono** [comment]
Looking into it

**Comment by NextinMono** [comment]
Fixed by making the ThemeManager inactive, also found another bug within this one and I fixed that too.
It'll be included in the next private beta.

**Comment by rocketbucket10** [comment]
in the level where you are going to get the ability unlocked, you can still change colors (before you get the abilty)

**Comment by rocketbucket10** [comment]
in that same level, during the cutscene you can successfully change colors, and it causes music overlapping and framerate issues. 

https://streamable.com/1nipw2

**Comment by NextinMono** [comment]
Okay I made extra checks this time, now it shouldn't do that anymore
