### ISSUE TITLE
Esc can be pressed during cutscenes, causes several issues.

### ISSUE THREAD

**Issue by rocketbucket10** [teamspettro/monospace-game-bugs#6]
https://streamable.com/zax3s2

https://streamable.com/rt4a0h

During the cutscene if you constantly press Esc, you can lag the cutscene.
If you hold down Esc, you can completely stop the cutscene, if you hold down Esc again the cutscene will behave normally.

**Comment by NextinMono** [comment]
Should be fixed. I added a new parameter that will block pausing completely.
