### ISSUE TITLE
WR behaves irregulary.

### ISSUE THREAD

**Issue by rocketbucket10** [teamspettro/monospace-game-bugs#8]
https://streamable.com/i9c115

After you finish the dialogue with WR, WR gets stuck inside you, and causes lag.

**Comment by NextinMono** [comment]
Was fixed after the latest private build

**Comment by rocketbucket10** [comment]
TB5 still has this issue.

**Comment by NextinMono** [comment]
Okay I actually found the cause of the issue.
Not too long ago I had to remake the ragdoll for WR, and I had to reconfigure the script too, so I forgot to update some values.
*SHOULD*'ve been fixed, but knowing _unity_ it probably didn't update everywhere.
